scrape_configs:
  - job_name: 'quiz-app'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 2s
    static_configs:
      - targets: ['host.docker.internal:8080','localhost:9090']
        labels:
          application: 'quiz-app-backend'
